import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { expect, test } from "@playwright/test";
import { PREVIEW_URL } from "../../scripts/ports.mjs";

/**
 * Page-level SEO invariants (openspec: fix-seo-hreflang-canonical-meta).
 *
 * Four things must hold on every URL the site publishes:
 *   1. exactly one <meta name="description">, and no two URLs share its text
 *   2. <link rel="canonical"> points at the URL that was fetched, /en included
 *   3. every hreflang href is a URL that sitemap.xml actually lists
 *   4. hreflang in the HTML agrees with the xhtml:link pairs in sitemap.xml
 * plus: a translated article carries an <a href> to its counterpart, so the
 * other language version sits in the crawler's link graph.
 *
 * These fail as a set, not individually — the audit that motivated this file
 * found the same page shipping a description from index.html, a canonical
 * pointing at the other language, and hreflang built by string surgery.
 *
 * Runs against the preview build, not the dev server: under
 * <React.StrictMode> react-helmet-async 2.0.5 + React 19 never commit their
 * <meta>/<link> tags, so the dev server shows an empty <head> regardless of
 * what the code does. StrictMode is development-only, so the build is the
 * honest target — and it is also what Vercel actually serves.
 */

const SITE_URL = "https://pawel.lipowczan.pl";

const sitemapPath = fileURLToPath(
  new URL("../../public/sitemap.xml", import.meta.url),
);

/**
 * sitemap.xml → { "<loc>": { pl: "...", en: "...", "x-default": "..." } }
 *
 * Regex rather than a parser: the file is generated by
 * scripts/update-sitemap.js with a fixed shape, and pulling in an XML
 * dependency for two element types is not worth it.
 */
const parseSitemap = () => {
  const xml = readFileSync(sitemapPath, "utf8");
  const entries = new Map();

  for (const block of xml.match(/<url>[\s\S]*?<\/url>/g) ?? []) {
    const loc = block.match(/<loc>([^<]+)<\/loc>/)?.[1];
    if (!loc) continue;

    const alternates = {};
    const linkRe =
      /<xhtml:link\s+rel="alternate"\s+hreflang="([^"]+)"\s+href="([^"]+)"\s*\/>/g;
    let match;
    while ((match = linkRe.exec(block)) !== null) {
      alternates[match[1]] = match[2];
    }

    entries.set(loc, alternates);
  }

  return entries;
};

const SITEMAP = parseSitemap();
const SITEMAP_LOCS = new Set(SITEMAP.keys());

/**
 * The URL set from the change's task 5.7. `/llm-wiki/kurs/...` stands in for
 * "an article without a translation": every blog post in the repo currently
 * has an `alternateSlug`, while the course is PL-only, so it exercises the
 * same branch — a page that must emit no hreflang at all.
 */
const PAGES = [
  { path: "/", label: "PL home" },
  { path: "/en/", label: "EN home" },
  { path: "/blog", label: "PL blog listing" },
  { path: "/blog/slabe-strony-claude-code", label: "PL post with translation" },
  {
    path: "/en/blog/claude-code-weak-spots",
    label: "EN post with translation",
  },
  { path: "/en/privacy-policy", label: "EN legal page" },
  { path: "/projects/frontdesk-ai", label: "PL project page" },
  {
    path: "/llm-wiki/kurs/0-co-to-drugi-mozg",
    label: "PL-only page (no translation)",
  },
  // Three posts keep the same slug in both languages, so `alternateSlug`
  // equals the post's own slug: no-code-lead-generation,
  // remotion-explainer-videos-ai and second-brain-obsidian-claude-code-skills.
  // Resolving the pair by slug alone picked an arbitrary one of the two and
  // yielded no alternate, which silently dropped hreflang from all six URLs.
  //
  // The pair below covers that path in both directions; the other two behave
  // identically and are left out to keep this suite short. What guards all
  // three is the sitemap comparison every entry here runs — a post that loses
  // its hreflang fails against its own `xhtml:link` pairs.
  {
    path: "/blog/no-code-lead-generation",
    label: "PL post sharing its slug with the EN version",
  },
  {
    path: "/en/blog/no-code-lead-generation",
    label: "EN post sharing its slug with the PL version",
  },
];

/** Canonical form of a site URL, so a trailing slash never decides a match. */
const normalize = (url) => url.replace(/\/+$/, "") || "/";

/** Navigate and let react-helmet-async write the tags into <head>. */
const openPage = async (page, path) => {
  await page.goto(path);
  await page.waitForLoadState("networkidle");
  await expect(page.locator('link[rel="canonical"]')).toHaveCount(1, {
    timeout: 15000,
  });
};

const readHreflang = (page) =>
  page.$$eval('link[rel="alternate"][hreflang]', (links) =>
    links.map((l) => ({
      hreflang: l.getAttribute("hreflang"),
      href: l.getAttribute("href"),
    })),
  );

test.describe("SEO — page metadata invariants", () => {
  test.use({ baseURL: PREVIEW_URL });

  // Serwer preview startuje tylko pod `PW_PREVIEW=1` — patrz
  // playwright.config.js. Bez niego nie ma czego odpytać, więc blok pomija
  // się z nazwą zmiennej zamiast wywracać przebieg na odmowie połączenia.
  // W CI zmienną ustawia workflow, w jobie chromium.
  test.skip(
    !process.env.PW_PREVIEW,
    "Serwer preview nie działa — uruchom z PW_PREVIEW=1, żeby wykonać ten blok."
  );

  test("sitemap.xml parsed and every checked path is listed in it", () => {
    expect(SITEMAP.size).toBeGreaterThan(0);

    for (const { path, label } of PAGES) {
      const expected = normalize(`${SITE_URL}${path}`);
      const listed = [...SITEMAP_LOCS].some(
        (loc) => normalize(loc) === expected,
      );
      expect(listed, `${label} (${path}) missing from sitemap.xml`).toBe(true);
    }
  });

  for (const { path, label } of PAGES) {
    test(`${label} (${path}) — description, canonical, hreflang`, async ({
      page,
    }) => {
      await openPage(page, path);

      // 1. Exactly one description tag. Two of them (the old static one in
      //    index.html plus the one React renders) let a parser pick the wrong
      //    one.
      const descriptions = await page.$$eval(
        'meta[name="description"]',
        (metas) => metas.map((m) => m.getAttribute("content")),
      );
      expect(descriptions).toHaveLength(1);
      expect(descriptions[0]?.trim().length ?? 0).toBeGreaterThan(0);

      // 1a. Exactly one <title>, for the same reason. react-helmet-async used
      //     to overwrite the text of the static tag in index.html, so a second
      //     title was impossible; React 19 hoists a new element instead, which
      //     is why that static tag had to go.
      await expect(page.locator("title")).toHaveCount(1);

      // 2. Canonical points at this page, /en prefix kept.
      const canonical = await page
        .locator('link[rel="canonical"]')
        .getAttribute("href");
      expect(normalize(canonical)).toBe(normalize(`${SITE_URL}${path}`));

      const hreflangLinks = await readHreflang(page);

      // 3. No invented URLs: every hreflang href is a sitemap <loc>.
      for (const { hreflang, href } of hreflangLinks) {
        const known = [...SITEMAP_LOCS].some(
          (loc) => normalize(loc) === normalize(href),
        );
        expect(
          known,
          `hreflang="${hreflang}" → ${href} is not a <loc> in sitemap.xml`,
        ).toBe(true);
      }

      // 4. HTML and sitemap must not contradict each other.
      const sitemapEntry = [...SITEMAP.entries()].find(
        ([loc]) => normalize(loc) === normalize(`${SITE_URL}${path}`),
      )?.[1];
      expect(sitemapEntry).toBeDefined();

      // 4a. Nothing in the HTML that the sitemap does not declare.
      for (const { hreflang, href } of hreflangLinks) {
        expect(
          normalize(sitemapEntry[hreflang] ?? ""),
          `hreflang="${hreflang}" disagrees with sitemap.xml`,
        ).toBe(normalize(href));
      }

      // 4b. Nothing missing from the HTML that the sitemap declares as a real
      //     cross-language link. Self-referential entries (a PL-only page
      //     listing itself under hreflang="pl") are deliberately not mirrored
      //     into the HTML: hreflang without a reciprocal pair is ignored by
      //     Google anyway, so the component emits nothing.
      const emitted = new Set(hreflangLinks.map((l) => l.hreflang));
      const canonicalNormalized = normalize(`${SITE_URL}${path}`);
      for (const [hreflang, href] of Object.entries(sitemapEntry)) {
        if (normalize(href) === canonicalNormalized) continue;
        expect(
          emitted.has(hreflang),
          `sitemap.xml declares hreflang="${hreflang}" → ${href}, HTML does not`,
        ).toBe(true);
      }
    });
  }

  /**
   * Dane strukturalne należą do trasy, która je deklaruje.
   *
   * Do 2026-09-06 komponent StructuredData doklejał skrypt wprost do
   * `document.head`, poza drzewem Reacta, więc blok nie był związany z trasą:
   * `/privacy-policy` serwowała `Person` ze strony głównej mimo braku
   * jakiegokolwiek kodu od schematów u siebie, a `/en/` serwowała ten sam blok
   * dwa razy. Emisja idzie teraz przez Helmet, tak jak reszta nagłówka.
   *
   * Ten test siedzi tutaj, a nie w `breadcrumbs.spec.js`, z tego samego powodu
   * co reszta pliku: pod StrictMode Helmet nie wystawia tagów na serwerze
   * deweloperskim, więc jedyny uczciwy cel to build.
   */
  test("structured data belongs to the route that declares it", async ({
    page,
  }) => {
    const blocksOn = async (path, { awaitContent = false, expected = null } = {}) => {
      await page.goto(path);
      // Ciało artykułu i lekcji przychodzi osobnym `import()`, a schemat
      // `BlogPosting` powstaje dopiero z niego. Przed tym momentem hydratacja
      // zdejmuje bloki wypieczone w prerenderze, bo schemat jest jeszcze pusty.
      // `data-content-ready` na <html> to ten sam znacznik, na który czeka
      // scripts/prerender.mjs.
      if (awaitContent) {
        await page.waitForFunction(
          () => document.documentElement.dataset.contentReady === "true",
          null,
          { timeout: 10000 },
        );
      }
      const read = () =>
        page.evaluate(() =>
          [...document.querySelectorAll('script[type="application/ld+json"]')].map(
            (el) => el.textContent,
          ),
        );

      // Gdy spodziewamy się bloków, czekamy aż Helmet je wystawi. Gdy
      // spodziewamy się zera, odczyt natychmiastowy nic nie dowodzi — dajemy
      // stronie czas na ewentualny wyciek, zanim stwierdzimy, że go nie ma.
      if (expected === null) {
        await page.waitForTimeout(1000);
        return read();
      }
      await expect.poll(async () => (await read()).length).toBe(expected);
      return read();
    };

    // Strona bez własnych danych strukturalnych nie niesie cudzych.
    const legal = await blocksOn("/privacy-policy");
    expect(
      legal,
      "/privacy-policy carries structured data it does not declare",
    ).toHaveLength(0);

    // Strona, która deklaruje jeden blok, niesie go dokładnie raz.
    const en = await blocksOn("/en/", { expected: 1 });
    expect(en, "/en/ should carry exactly one block").toHaveLength(1);

    // Artykuł niesie własne bloki, każdy raz, w tym okruszki nawigacyjne.
    const post = await blocksOn("/blog/rag-ragowi-nierowny", {
      awaitContent: true,
      expected: 3,
    });
    expect(new Set(post).size, "article repeats a structured-data block").toBe(
      post.length,
    );
    const types = post.map((raw) => JSON.parse(raw)["@type"]);
    expect(types, "article is missing its BreadcrumbList").toContain(
      "BreadcrumbList",
    );
    expect(types, "article is missing its BlogPosting").toContain("BlogPosting");
  });

  /**
   * FAQPage huba kursu — asercja przeniesiona z `llm-wiki-course.spec.js`
   * 2026-09-06, z tego samego powodu co wyżej: pod StrictMode Helmet nie
   * wystawia tagów na serwerze deweloperskim, więc jedynym uczciwym celem jest
   * build. Sam widok FAQ testuje się dalej tam, gdzie testowały go asercje
   * wizualne.
   */
  test("course hub emits a FAQPage whose questions match the rendered list", async ({
    page,
  }) => {
    await page.goto("/llm-wiki/kurs");

    // Helmet wystawia tagi dopiero po hydratacji, więc odczyt tuż po `goto`
    // trafia w pustkę — w CI powtarzalnie. Odpytujemy, i bierzemy wartość z
    // tego samego sprawdzenia: drugi odczyt po udanym pollu potrafił trafić w
    // moment, gdy Helmet akurat przestawiał zawartość.
    let faqSchema = null;
    await expect
      .poll(
        async () => {
          faqSchema = await page.evaluate(() =>
            [...document.querySelectorAll('script[type="application/ld+json"]')]
              .map((el) => {
                try {
                  return JSON.parse(el.textContent);
                } catch {
                  return null;
                }
              })
              .find((data) => data && data["@type"] === "FAQPage"),
          );
          return Boolean(faqSchema?.mainEntity?.length);
        },
        { message: "course hub is missing its FAQPage block" },
      )
      .toBe(true);

    expect(faqSchema.mainEntity.length).toBeGreaterThanOrEqual(3);

    await expect(page.getByTestId("course-faq").locator("dt").first()).toBeVisible();

    const rendered = await page
      .getByTestId("course-faq")
      .locator("dt")
      .allTextContents();

    for (const { name } of faqSchema.mainEntity) {
      expect(
        rendered.some((text) => text.includes(name)),
        `FAQPage question not rendered on the page: ${name}`,
      ).toBe(true);
    }
  });

  test("descriptions are unique across pages", async ({ page }) => {
    // One navigation per page in a single test, so the comparison sees them
    // all — worth the extra wall clock, hence test.slow().
    test.slow();

    const seen = new Map();

    for (const { path, label } of PAGES) {
      await openPage(page, path);
      const description = await page
        .locator('meta[name="description"]')
        .getAttribute("content");

      const previous = seen.get(description);
      expect(
        previous,
        `${label} (${path}) repeats the description of ${previous}`,
      ).toBeUndefined();
      seen.set(description, path);
    }

    expect(seen.size).toBe(PAGES.length);
  });

  test("translated article links to its counterpart with a real href", async ({
    page,
  }) => {
    await openPage(page, "/blog/slabe-strony-claude-code");

    // The switcher renders as an anchor, and the target is resolved during
    // render — that is what puts the EN URL into the prerendered HTML.
    const switcher = page.locator('a[aria-label="Switch to English"]').first();
    await expect(switcher).toHaveCount(1);
    await expect(switcher).toHaveAttribute(
      "href",
      "/en/blog/claude-code-weak-spots",
    );

    // Client-side navigation still works and lands where the href points.
    await page
      .locator('a[aria-label="Switch to English"]:visible')
      .first()
      .click();
    await page.waitForURL("**/en/blog/claude-code-weak-spots", {
      timeout: 15000,
    });
  });

  test("page without a translation links to the other language listing", async ({
    page,
  }) => {
    await openPage(page, "/llm-wiki/kurs/0-co-to-drugi-mozg");

    const switcher = page.locator('a[aria-label="Switch to English"]').first();
    await expect(switcher).toHaveCount(1);

    // Prefix mirror is fine here — the switcher is a user affordance, not an
    // hreflang declaration. What matters is that no hreflang was emitted.
    await expect(page.locator('link[rel="alternate"][hreflang]')).toHaveCount(0);
  });

  /**
   * Metadata after a client-side route change (openspec:
   * migrate-seo-to-react19-metadata, decision D3).
   *
   * React 19 hoists <title>, <meta> and <link> into <head> by itself, but it
   * does not deduplicate <meta> by `name` — two components rendering a
   * description produce two tags. Here <SEO> renders once per route and
   * unmounts on the way out, so React should remove the previous page's tags.
   * "Should" is not enough for a layer that was just found silently broken,
   * so these tests prove it instead of assuming it.
   *
   * Every case asserts the transition happened without a document load. A full
   * reload would rebuild <head> from scratch and pass trivially, proving
   * nothing about unmount cleanup.
   */
  test.describe("po nawigacji po stronie klienta", () => {
    const POST_A = "/blog/slabe-strony-claude-code";
    const POST_B = "/blog/rag-ragowi-nierowny";
    const LESSON_WITHOUT_TRANSLATION = "/llm-wiki/kurs/0-co-to-drugi-mozg";

    /** Counts main-frame document loads from the moment it is attached. */
    const countDocumentLoads = (page) => {
      const counter = { loads: 0 };
      page.on("load", () => {
        counter.loads += 1;
      });
      return counter;
    };

    /**
     * A route change the router handles, with no <Link> to click.
     *
     * Nothing reaches /llm-wiki/kurs through the router: it is absent from the
     * nav and the footer, and the one article that mentions it does so with
     * raw HTML from markdown, which reloads the document. `pushState` plus a
     * `popstate` event is precisely what React Router subscribes to, so the
     * route swaps client-side — the condition under test.
     */
    const navigateClientSide = async (page, path) => {
      await page.evaluate((target) => {
        window.history.pushState({}, "", target);
        window.dispatchEvent(new PopStateEvent("popstate", { state: {} }));
      }, path);
      await page.waitForFunction(
        (target) => window.location.pathname === target,
        path,
      );
    };

    test("artykuł → artykuł: jeden opis, treść z artykułu docelowego", async ({
      page,
    }) => {
      // Three navigations in one test — the reference value has to come from a
      // real load of the target article, not from a string in the test.
      test.slow();

      await openPage(page, POST_B);
      const expected = await page
        .locator('meta[name="description"]')
        .getAttribute("content");
      expect(expected?.trim().length ?? 0).toBeGreaterThan(0);

      await openPage(page, POST_A);
      const before = await page
        .locator('meta[name="description"]')
        .getAttribute("content");
      expect(before).not.toBe(expected);

      const loads = countDocumentLoads(page);

      // The listing is the only page holding a <Link> to both articles.
      await page.locator(`a[href="/blog"]:visible`).first().click();
      await page.waitForURL("**/blog");
      await page.locator(`a[href="${POST_B}"]:visible`).first().click();
      await page.waitForURL(`**${POST_B}`);

      // The router updates the URL before React commits the new render, so
      // the tags lag the address by a frame or two. Retrying assertions, not a
      // single read — a one-shot read here catches the listing's description.
      await expect(page.locator('meta[name="description"]')).toHaveAttribute(
        "content",
        expected,
      );
      await expect(page.locator('meta[name="description"]')).toHaveCount(1);
      expect(loads.loads, "route change must not reload the document").toBe(0);
    });

    test("przełączenie języka: jeden canonical, na bieżącą wersję językową", async ({
      page,
    }) => {
      await openPage(page, POST_A);
      const loads = countDocumentLoads(page);

      await page
        .locator('a[aria-label="Switch to English"]:visible')
        .first()
        .click();
      await page.waitForURL("**/en/blog/claude-code-weak-spots", {
        timeout: 15000,
      });

      await expect
        .poll(async () =>
          normalize(
            await page
              .locator('link[rel="canonical"]')
              .first()
              .getAttribute("href"),
          ),
        )
        .toBe(normalize(`${SITE_URL}/en/blog/claude-code-weak-spots`));
      await expect(page.locator('link[rel="canonical"]')).toHaveCount(1);
      expect(loads.loads, "route change must not reload the document").toBe(0);
    });

    test("strona z parą hreflang → strona bez tłumaczenia: zero hreflang", async ({
      page,
    }) => {
      await openPage(page, POST_A);
      await expect(page.locator('link[rel="alternate"][hreflang]')).toHaveCount(
        3,
      );

      const loads = countDocumentLoads(page);
      await navigateClientSide(page, LESSON_WITHOUT_TRANSLATION);

      await expect(page.locator('link[rel="alternate"][hreflang]')).toHaveCount(
        0,
      );
      expect(loads.loads, "route change must not reload the document").toBe(0);
    });

    test("każde przejście zostawia dokładnie jeden <title>", async ({
      page,
    }) => {
      test.slow();

      await openPage(page, POST_A);
      await expect(page.locator("title")).toHaveCount(1);
      const first = await page.title();

      const loads = countDocumentLoads(page);

      // toHaveTitle retries, so it waits out the gap between the URL changing
      // and React committing the new <title>.
      await navigateClientSide(page, LESSON_WITHOUT_TRANSLATION);
      await expect(page).not.toHaveTitle(first);
      await expect(page.locator("title")).toHaveCount(1);

      await navigateClientSide(page, POST_A);
      await expect(page).toHaveTitle(first);
      await expect(page.locator("title")).toHaveCount(1);

      expect(loads.loads, "route change must not reload the document").toBe(0);
    });
  });
});
