import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { expect, test } from "@playwright/test";

/**
 * Page-level SEO invariants (openspec: fix-seo-hreflang-canonical-meta).
 *
 * Four things must hold on every URL the site publishes:
 *   1. exactly one <meta name="description">, and no two URLs share its text
 *   2. <link rel="canonical"> points at the URL that was fetched, /en included
 *   3. every hreflang href is a URL that sitemap.xml actually lists
 *   4. hreflang in the HTML agrees with the xhtml:link pairs in sitemap.xml
 * plus: a translated article carries an <a href> to its counterpart, so the
 * other language version sits in the crawler's link graph.
 *
 * These fail as a set, not individually — the audit that motivated this file
 * found the same page shipping a description from index.html, a canonical
 * pointing at the other language, and hreflang built by string surgery.
 *
 * Runs against the preview build (4173), not the dev server: under
 * <React.StrictMode> react-helmet-async 2.0.5 + React 19 never commit their
 * <meta>/<link> tags, so the dev server shows an empty <head> regardless of
 * what the code does. StrictMode is development-only, so the build is the
 * honest target — and it is also what Vercel actually serves.
 */

const SITE_URL = "https://pawel.lipowczan.pl";

const sitemapPath = fileURLToPath(
  new URL("../../public/sitemap.xml", import.meta.url),
);

/**
 * sitemap.xml → { "<loc>": { pl: "...", en: "...", "x-default": "..." } }
 *
 * Regex rather than a parser: the file is generated by
 * scripts/update-sitemap.js with a fixed shape, and pulling in an XML
 * dependency for two element types is not worth it.
 */
const parseSitemap = () => {
  const xml = readFileSync(sitemapPath, "utf8");
  const entries = new Map();

  for (const block of xml.match(/<url>[\s\S]*?<\/url>/g) ?? []) {
    const loc = block.match(/<loc>([^<]+)<\/loc>/)?.[1];
    if (!loc) continue;

    const alternates = {};
    const linkRe =
      /<xhtml:link\s+rel="alternate"\s+hreflang="([^"]+)"\s+href="([^"]+)"\s*\/>/g;
    let match;
    while ((match = linkRe.exec(block)) !== null) {
      alternates[match[1]] = match[2];
    }

    entries.set(loc, alternates);
  }

  return entries;
};

const SITEMAP = parseSitemap();
const SITEMAP_LOCS = new Set(SITEMAP.keys());

/**
 * The URL set from the change's task 5.7. `/llm-wiki/kurs/...` stands in for
 * "an article without a translation": every blog post in the repo currently
 * has an `alternateSlug`, while the course is PL-only, so it exercises the
 * same branch — a page that must emit no hreflang at all.
 */
const PAGES = [
  { path: "/", label: "PL home" },
  { path: "/en/", label: "EN home" },
  { path: "/blog", label: "PL blog listing" },
  { path: "/blog/slabe-strony-claude-code", label: "PL post with translation" },
  {
    path: "/en/blog/claude-code-weak-spots",
    label: "EN post with translation",
  },
  { path: "/en/privacy-policy", label: "EN legal page" },
  { path: "/projects/frontdesk-ai", label: "PL project page" },
  {
    path: "/llm-wiki/kurs/0-co-to-drugi-mozg",
    label: "PL-only page (no translation)",
  },
];

/** Canonical form of a site URL, so a trailing slash never decides a match. */
const normalize = (url) => url.replace(/\/+$/, "") || "/";

/** Navigate and let react-helmet-async write the tags into <head>. */
const openPage = async (page, path) => {
  await page.goto(path);
  await page.waitForLoadState("networkidle");
  await expect(page.locator('link[rel="canonical"]')).toHaveCount(1, {
    timeout: 15000,
  });
};

const readHreflang = (page) =>
  page.$$eval('link[rel="alternate"][hreflang]', (links) =>
    links.map((l) => ({
      hreflang: l.getAttribute("hreflang"),
      href: l.getAttribute("href"),
    })),
  );

test.describe("SEO — page metadata invariants", () => {
  test.use({ baseURL: "http://localhost:4173" });

  test("sitemap.xml parsed and every checked path is listed in it", () => {
    expect(SITEMAP.size).toBeGreaterThan(0);

    for (const { path, label } of PAGES) {
      const expected = normalize(`${SITE_URL}${path}`);
      const listed = [...SITEMAP_LOCS].some(
        (loc) => normalize(loc) === expected,
      );
      expect(listed, `${label} (${path}) missing from sitemap.xml`).toBe(true);
    }
  });

  for (const { path, label } of PAGES) {
    test(`${label} (${path}) — description, canonical, hreflang`, async ({
      page,
    }) => {
      await openPage(page, path);

      // 1. Exactly one description tag. Two of them (the old static one in
      //    index.html plus Helmet's) let a parser pick the wrong one.
      const descriptions = await page.$$eval(
        'meta[name="description"]',
        (metas) => metas.map((m) => m.getAttribute("content")),
      );
      expect(descriptions).toHaveLength(1);
      expect(descriptions[0]?.trim().length ?? 0).toBeGreaterThan(0);

      // 2. Canonical points at this page, /en prefix kept.
      const canonical = await page
        .locator('link[rel="canonical"]')
        .getAttribute("href");
      expect(normalize(canonical)).toBe(normalize(`${SITE_URL}${path}`));

      const hreflangLinks = await readHreflang(page);

      // 3. No invented URLs: every hreflang href is a sitemap <loc>.
      for (const { hreflang, href } of hreflangLinks) {
        const known = [...SITEMAP_LOCS].some(
          (loc) => normalize(loc) === normalize(href),
        );
        expect(
          known,
          `hreflang="${hreflang}" → ${href} is not a <loc> in sitemap.xml`,
        ).toBe(true);
      }

      // 4. HTML and sitemap must not contradict each other.
      const sitemapEntry = [...SITEMAP.entries()].find(
        ([loc]) => normalize(loc) === normalize(`${SITE_URL}${path}`),
      )?.[1];
      expect(sitemapEntry).toBeDefined();

      // 4a. Nothing in the HTML that the sitemap does not declare.
      for (const { hreflang, href } of hreflangLinks) {
        expect(
          normalize(sitemapEntry[hreflang] ?? ""),
          `hreflang="${hreflang}" disagrees with sitemap.xml`,
        ).toBe(normalize(href));
      }

      // 4b. Nothing missing from the HTML that the sitemap declares as a real
      //     cross-language link. Self-referential entries (a PL-only page
      //     listing itself under hreflang="pl") are deliberately not mirrored
      //     into the HTML: hreflang without a reciprocal pair is ignored by
      //     Google anyway, so the component emits nothing.
      const emitted = new Set(hreflangLinks.map((l) => l.hreflang));
      const canonicalNormalized = normalize(`${SITE_URL}${path}`);
      for (const [hreflang, href] of Object.entries(sitemapEntry)) {
        if (normalize(href) === canonicalNormalized) continue;
        expect(
          emitted.has(hreflang),
          `sitemap.xml declares hreflang="${hreflang}" → ${href}, HTML does not`,
        ).toBe(true);
      }
    });
  }

  test("descriptions are unique across pages", async ({ page }) => {
    // One navigation per page in a single test, so the comparison sees them
    // all — worth the extra wall clock, hence test.slow().
    test.slow();

    const seen = new Map();

    for (const { path, label } of PAGES) {
      await openPage(page, path);
      const description = await page
        .locator('meta[name="description"]')
        .getAttribute("content");

      const previous = seen.get(description);
      expect(
        previous,
        `${label} (${path}) repeats the description of ${previous}`,
      ).toBeUndefined();
      seen.set(description, path);
    }

    expect(seen.size).toBe(PAGES.length);
  });

  test("translated article links to its counterpart with a real href", async ({
    page,
  }) => {
    await openPage(page, "/blog/slabe-strony-claude-code");

    // The switcher renders as an anchor, and the target is resolved during
    // render — that is what puts the EN URL into the prerendered HTML.
    const switcher = page.locator('a[aria-label="Switch to English"]').first();
    await expect(switcher).toHaveCount(1);
    await expect(switcher).toHaveAttribute(
      "href",
      "/en/blog/claude-code-weak-spots",
    );

    // Client-side navigation still works and lands where the href points.
    await page
      .locator('a[aria-label="Switch to English"]:visible')
      .first()
      .click();
    await page.waitForURL("**/en/blog/claude-code-weak-spots", {
      timeout: 15000,
    });
  });

  test("page without a translation links to the other language listing", async ({
    page,
  }) => {
    await openPage(page, "/llm-wiki/kurs/0-co-to-drugi-mozg");

    const switcher = page.locator('a[aria-label="Switch to English"]').first();
    await expect(switcher).toHaveCount(1);

    // Prefix mirror is fine here — the switcher is a user affordance, not an
    // hreflang declaration. What matters is that no hreflang was emitted.
    await expect(page.locator('link[rel="alternate"][hreflang]')).toHaveCount(0);
  });
});
