#!/usr/bin/env node
/**
 * Downloads the web fonts we self-host and regenerates src/styles/fonts.css.
 *
 * We serve Inter and Fira Code from our own origin instead of fonts.googleapis.com
 * so that no page load depends on a third-party origin. Run this only when a font
 * needs updating; the output is committed.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Only the `latin` and `latin-ext` subsets are kept. latin-ext is not optional —
 * it carries ą ć ę ł ń ó ś ź ż, so dropping it would silently fall back to a
 * system font for most Polish text on the site.
 *
 * Both families are SIL Open Font License 1.1, which permits redistribution; the
 * license is written next to the files.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const FONT_DIR = resolve(ROOT, "public/fonts");
const CSS_OUT = resolve(ROOT, "src/styles/fonts.css");

// A modern UA is required — Google serves woff2 + variable axes only to browsers
// it recognises, and older/unknown agents get much larger ttf files.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

const FAMILIES = [
  {
    // 300-700 covers every weight the site actually uses: font-light (300),
    // body (400), font-medium (500), font-semibold (600), font-bold (700).
    // The old @import pulled 300-900; 800 and 900 were never referenced.
    name: "Inter",
    query: "Inter:wght@300..700",
    slug: "inter",
  },
  {
    name: "Fira Code",
    query: "Fira+Code:wght@400..600",
    slug: "fira-code",
  },
];

const get = async (url, asBuffer = false) => {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return asBuffer ? Buffer.from(await res.arrayBuffer()) : res.text();
};

/** Splits Google's CSS into blocks, each tagged with the `/* subset *\/` comment above it. */
const parseFaces = (css) => {
  const faces = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m;
  while ((m = re.exec(css)) !== null) faces.push({ subset: m[1], block: m[2] });
  return faces;
};

const field = (block, prop) => {
  const m = block.match(new RegExp(`${prop}:\\s*([^;]+);`));
  return m ? m[1].trim() : null;
};

const main = async () => {
  await mkdir(FONT_DIR, { recursive: true });
  const chunks = [
    "/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.",
    " * Self-hosted so no page load depends on fonts.googleapis.com / fonts.gstatic.com.",
    " */",
    "",
  ];

  for (const family of FAMILIES) {
    const css = await get(
      `https://fonts.googleapis.com/css2?family=${family.query}&display=swap`,
    );
    const faces = parseFaces(css).filter((f) => KEEP_SUBSETS.has(f.subset));
    if (faces.length === 0) throw new Error(`no latin subsets found for ${family.name}`);

    for (const { subset, block } of faces) {
      const url = field(block, "src")?.match(/url\((https:[^)]+)\)/)?.[1];
      if (!url) throw new Error(`no woff2 url in ${family.name}/${subset}`);

      const file = `${family.slug}-${subset}.woff2`;
      const bytes = await get(url, true);
      await writeFile(resolve(FONT_DIR, file), bytes);
      console.log(`  ${file}  ${(bytes.length / 1024).toFixed(1)} kB`);

      chunks.push(
        "@font-face {",
        `  font-family: "${family.name}";`,
        `  font-style: ${field(block, "font-style") ?? "normal"};`,
        // A range like `300 700` marks this as a variable font: one file covers
        // every weight in between, so there is nothing to pick per weight.
        `  font-weight: ${field(block, "font-weight")};`,
        "  font-display: swap;",
        `  src: url("/fonts/${file}") format("woff2");`,
        `  unicode-range: ${field(block, "unicode-range")};`,
        "}",
        "",
      );
    }
  }

  await writeFile(CSS_OUT, chunks.join("\n"), "utf8");
  console.log(`\nwrote ${CSS_OUT}`);
};

main().catch((err) => {
  console.error(`fetch-fonts failed: ${err.message}`);
  process.exit(1);
});
